version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - DJANGO_SETTINGS_MODULE=car_analysis_project.settings
    volumes:
      - ./media:/app/media
      - ./CarDentDetector/Weights:/app/CarDentDetector/Weights:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3
