# Generated by Django 5.2.6 on 2025-09-14 14:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='car_images/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('gemini_integrity_label', models.CharField(choices=[('damaged', 'Damaged'), ('undamaged', 'Undamaged')], max_length=20)),
                ('gemini_integrity_confidence', models.FloatField()),
                ('gemini_cleanliness_label', models.CharField(choices=[('clean', 'Clean'), ('slightly_dirty', 'Slightly Dirty'), ('dirty', 'Dirty')], max_length=20)),
                ('gemini_cleanliness_confidence', models.FloatField()),
                ('gemini_damage_details', models.JSONField(default=dict)),
                ('gemini_environment', models.JSONField(default=dict)),
                ('gemini_uncertain', models.BooleanField(default=False)),
                ('gemini_notes', models.TextField(blank=True)),
                ('yolo_detections', models.JSONField(default=list)),
                ('yolo_confidence', models.FloatField(blank=True, null=True)),
                ('processing_time', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Car Analysis',
                'verbose_name_plural': 'Car Analyses',
                'ordering': ['-created_at'],
            },
        ),
    ]
