# Generated by Django 5.2.6 on 2025-09-14 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_detector', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='caranalysis',
            name='processed_image',
            field=models.ImageField(blank=True, null=True, upload_to='processed_images/'),
        ),
    ]
